### ISSUE TITLE
Rust Hacks at Cummins

### ISSUE THREAD

**Issue by risbansal** [rusthacks/Rust#3]
## Event name

 - **Date:** 17/03/2018
 - **Location:** Mechanical Auditorium, Cummins College, Pune
 - **Expected number of attendees:** 60

### List of talks:
Speaker: Mehul Patel
links: about.me/rowdymehul
Topic: Rust

Speaker: Rishita Bansal
Links:
reps.mozilla.org/u/risbansal
twitter: risbansal
Topic: Virtual Reality and Augmented Reality

### Resource links:
Rust:
https://github.com/rusthacks

VR and AR:
www.aframe.io
www.mozvr.com

**Comment by nomadicmehul** [comment]
Thanks for sharing @risbansal Looking forward
